steps:
  # copy secrets
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://watchdog-secrets/.env', './services/.env']
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/services:$SHORT_SHA', '.' ]
  dir: services
  # tests
- name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['up', '--abort-on-container-exit']
  dir: services
  # deploy container image to cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'services', '--image', 'gcr.io/$PROJECT_ID/services:$SHORT_SHA', '--region', 'us-central1','--platform', 'managed']
images: ['gcr.io/$PROJECT_ID/services:$SHORT_SHA']
